export const dnbCodes = {
  LIST_DRUGS: "DNB_LIST_DRUGS",
  READ_DRDS: "DNB_READ_DRDS",
  EDIT_DRDS: "DNB_EDIT_DRDS",
  DOWNLOAD_APPROVED_DRD: "DNB_DOWNLOAD_APPROVED_DRD",
  DOWNLOAD_DRAFT_DRD: "DNB_DOWNLOAD_DRAFT_DRD",
  REASSIGN_EDITOR: "DNB_REASSIGN_EDITOR",
  REASSIGN_APPROVER: "DNB_REASSIGN_APPROVER",
  REVIEW_APPROVE_DRD: "DNB_REVIEW_APPROVE_DRD",
  READ_MIDRULE_TEMPLATE: "DNB_READ_MIDRULE_TEMPLATE",
  EDIT_MIDRULE_TEMPLATE: "DNB_EDIT_MIDRULE_TEMPLATE",
};
