export enum behaviors {
  copyRow = "copyRow",
  undoCopyRow = "undoCopyRow",
  copyRowGroup = "copyRowGroup",
  undoCopyRowGroup = "undoCopyRowGroup",
  copyGroup = "copyGroup",
  undoCopyGroup = "undoCopyGroup",
  copyColumn = "copyColumn",
  pasteColumn = "pasteColumn",
  removeRow = "removeRow",
  removeGroup = "removeGroup",
  addRow = "addRow",
  addManyRows = "addManyRows",
  addGroup = "addGroup",
  movedRow = "movedRow",
  movedGroup = "movedGroup",
  addGroupRow = "addGroupRow",
  duplicateDosing = "duplicateDosing",
  newChanged = "newChanged",
  addMidRule = "addMidRule",
  detailEdit = "detailEdit",
  addExistingMidRule = "addExistingMidRule",
  addFeedback = "addFeedback",
  checkFeedback = "checkFeedback",
  removeMultipleRows = "removeMultipleRows",
  cancelMultiSelectRows = "cancelMultiSelectRows",
  confirmRemoveMultipleRows = "confirmRemoveMultipleRows",
  removeMultipleGroups = "removeMultipleGroups",
  confirmRemoveMultipleGruped = "confirmRemoveMultipleGruped",
  cancelMultiSelectGroupsM = "cancelMultiSelectGroupsM",
  undoRemoveMultiSelect = "undoRemoveMultiSelect",
  addComment = "addComment",
  editComment = "editComment",
  indicationRemove ="indicationRemove",
  indicationAdded = "indicationAdded"
}

export enum arrowNavigation {
  up = "moveup",
  down = "movedown",
  left = "moveleft",
  right = "moveright",
}
