export enum SectionCode {
  GeneralInformation = "UI-S-GINFO",
  References = "UI-S-REF",
  LCD = "UI-S-LCD",
  MedicalJournal = "UI-S-MEDJ",
  Indications = "UI-S-INDIC",
  Notes = "UI-S-NOTE",
  DiagnosisCodes = "UI-S-DIAGC",
  DailyMaxUnits = "UI-S-DMAXUNIT",
  DiagnosticCodeSummary = "UI-S-DIAGCS",
  ManifestationCodes = "UI-S-MANIFC",
  MaximumFrequency = "UI-S-MAXFREQ",
  Age = "UI-S-AGE",
  DailyMaximumDose = "UI-S-DMAXDOSE",
  Gender = "UI-S-GENDER",
  UnitsOverTime = "UI-S-UOT",
  VisitOverTime = "UI-S-VOT",
  CombinationTherapy = "UI-S-COMBIT",
  DosingPatterns = "UI-S-DOSPAT",
  DiagnosisCodeOverlaps = "UI-S-DCODOV",
  GlobalReviewIndications = "UI-S-GLIND",
  SecondaryMalignancy = "UI-S-SECMAL",
  GlobalReviewCodes = "UI-S-GLICD10",
  Rules = "UI-S-RULES",
}
