export class EclIcmsNotifiedRulesDto {
    icmsNotifiedRuleId: number;
    ruleId: number;
    changeSource: string;
    cvcode: string;
    eclnumber: string;
    tempRuleNumber: string;
    permRuleNumber: string;
    versionNumber = '1';
    implementationDt: Date;
    clients: any[] = [];
    analyst: any;
    writtenBy: any;
    description: string;
    resolvedDescription: string;
    medicalPolicy: string ;
    policyTypes: string;
    productType: string;
    claimTypes: any;
    primaryRefTitle: any;
    primaryCoreEnh: string;
    secondaryRefTitle: any;
    secondaryCoreEnh: string;
    subRuleDosFrom: Date;
    subRuleDosTo: Date;
    referenceDetails: string;
    lob: any;
    industryUpdateReqd: any;
    motherBabyFlag: number;
    libraryStatus: number;
    reasonCodes: any;
    oss: number;
    onlyDefinedFlag: number;
    claimTypeLink: number;
    podEligible: number;
    realTimeEligible: number;
    editFlag: number;
    cvCode: any;
    cvSource: number;
    purpose: string;
    prid: string;
    citRemarks: string;
    script: string;
    rationale: string;
    underReview: number;
    status: string;
    notes: string;
    priority: string;
    crossProduct: string;
    duplicateChecking: any;
    ruleReview: string;
    lagPolicyApplies: number;
    lagPolicyComments: string;
    medicalDirector: any;
    mdComments: string;
    approvalSentDt: Date;
    approvedDt: Date;
    rejectionReason: string;
    attachment1: any;
    attachment2: any;
    comments: string;
    history: string;
    modifiedBy: string;
    modifiedOn: Date;
    createdBy: any;
    midRuleDesc: string;
    targetRelease: string;
    instructions: string;
    templateStatus: string;
    pridDetails: any;
    claimTypesICM: any;
    claimTypesICMO: any;
}


