import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ECLConstantsService {

  ACTIVE_STATUS: number;
  INACTIVE_STATUS: number;

  RULE_STATUS_DRAFT: number;
  RULE_STATUS_IDEA: number;
  RULE_STATUS_NEW_IDEA: number;
  RULE_STATUS_EXISTING_IDEA: number;
  RULE_STATUS_VALID_IDEA: number;
  RULE_STAGE_LIBRARY_RULE: number;
  RULE_STATUS_IDEA_NOT_ASSIGNED: number;
  RULE_STATUS_IDEA_ASSIGNED: number;
  RULE_STATUS_IDEA_RETURNED: number;
  RULE_STAGE_PROVISIONAL_RULE: number;
  RULE_STATUS_IMPACTED: number;

  USERS_MEDICAL_DIRECTOR_ROLE: number;
  USERS_POLICY_OWNER_ROLE: number;
  USERS_CLINICAL_CONTENT_ANALYST: number;
  USERS_CCA: String;

  MEDICAL_DIRECTOR_APPROVAL_NEEDED: number;
  MEDICAL_DIRECTOR_APPROVAL_NEEDED_RETURNED: number;
  MEDICAL_DIRECTOR_APPROVAL_NEEDED_PROVISIONAL: number;
  MEDICAL_DIRECTOR_APPROVAL_NEEDED_PROVISIONAL_RETURNED: number;

  RULE_IMPACT_TYPE_EDITORIAL: number;
  RULE_IMPACT_TYPE_LOGICAL: number;

  LOOKUP_TYPE_RULE_IMPACT_TYPE: string;
  LOOKUP_TYPE_ICMS_CV_SOURCE: string;
  LOOKUP_TYPE_ICMS_INDUSTRY_UPDATE: string;
  LOOKUP_TYPE_ICMS_MOTHER_BABY_FLAG: string;
  LOOKUP_TYPE_ICMS_CLAIM_TYPE: string;
  LOOKUP_TYPE_ICMS_LIBRARY_STATUS: string;
  LOOKUP_TYPE_ICMS_OOS: string;
  LOOKUP_TYPE_ICMS_CLAIM_TYPE_LINK: string;
  LOOKUP_TYPE_ICMS_CV_CODE: string;
  LOOKUP_TYPE_ICMS_MEDICAL_POLICY: string;
  LOOKUP_TYPE_ICMS_CHANGE_SOURCE: string;
  LOOKUP_TYPE_ICMS_REASON_CODES: string;
  LOOKUP_TYPE_ICMS_POLICY_TYPES: string;
  LOOKUP_TYPE_ICMS_REF_TITLE: string;
  LOOKUP_TYPE_PROC_CODE_TYPE: string;
  LOOKUP_TYPE_PROC_CODE_OPTION: string;

  LOOKUP_CODE_EDITORIAL: string;
  LOOKUP_CODE_LOGICAL: string;
  LOOKUP_CODE_DENY: string;
  LOOKUP_CODE_BILLED_WITH_OR: string;
  LOOKUP_CODE_BILLED_WITH_AND: string;
  LOOKUP_CODE_BILLED_WITHOUT_OR: string;
  LOOKUP_CODE_BILLED_WITHOUT_AND: string;
  LOOKUP_CODE_DENYO: string;
  NEW_FILE: string
  EXISTING_FILE : string
  RULE_CODES_FILE : string
  RULE_STAGE_PROVISIONAL_RULE_DESCRIPTION: string;

  RULE_STAGE_DESCRIPTION: string;

  ROWS_PER_PAGE_OPTIONS: number[];

  SMALL_VERSION : string;
  LONG_VERSION  : string;



  constructor() {
    this.ACTIVE_STATUS = 1;
    this.INACTIVE_STATUS = 2;

    this.RULE_STATUS_DRAFT = 1;
    this.RULE_STATUS_IDEA = 2;
    this.RULE_STATUS_NEW_IDEA = 3;
    this.RULE_STATUS_EXISTING_IDEA = 4;
    this.RULE_STATUS_VALID_IDEA = 5;
    this.RULE_STATUS_IDEA_NOT_ASSIGNED = 8;
    this.RULE_STATUS_IDEA_ASSIGNED = 9;
    this.RULE_STATUS_IDEA_RETURNED = 10;
    this.RULE_STAGE_LIBRARY_RULE = 3;
    this.RULE_STAGE_PROVISIONAL_RULE = 2;
    this.RULE_STATUS_IMPACTED = 15;


    this.USERS_POLICY_OWNER_ROLE = 11;
    this.USERS_MEDICAL_DIRECTOR_ROLE = 10;
    this.USERS_CLINICAL_CONTENT_ANALYST = 12;

    this.USERS_CCA = "CCA"

    this.MEDICAL_DIRECTOR_APPROVAL_NEEDED = 60;
    this.MEDICAL_DIRECTOR_APPROVAL_NEEDED_RETURNED = 1639;
    this.MEDICAL_DIRECTOR_APPROVAL_NEEDED_PROVISIONAL = 65;
    this.MEDICAL_DIRECTOR_APPROVAL_NEEDED_PROVISIONAL_RETURNED = 1638;

    this.RULE_IMPACT_TYPE_EDITORIAL = 67;
    this.RULE_IMPACT_TYPE_LOGICAL = 68;
    this.RULE_STAGE_PROVISIONAL_RULE_DESCRIPTION = 'Provisional Rule';
    this.RULE_STAGE_DESCRIPTION = 'RULE';

    this.LOOKUP_TYPE_RULE_IMPACT_TYPE = 'RULE_IMPACT_TYPE';
    this.LOOKUP_TYPE_ICMS_CV_SOURCE = 'ICMS_CV_SOURCE';
    this.LOOKUP_TYPE_ICMS_INDUSTRY_UPDATE = 'ICMS_INDUSTRY_UPDATE';
    this.LOOKUP_TYPE_ICMS_MOTHER_BABY_FLAG = 'ICMS_MOTHER_BABY_FLAG';
    this.LOOKUP_TYPE_ICMS_CLAIM_TYPE = 'ICMS_CLAIM_TYPE';
    this.LOOKUP_TYPE_ICMS_LIBRARY_STATUS = 'ICMS_LIBRARY_STATUS';
    this.LOOKUP_TYPE_ICMS_OOS = 'ICMS_OOS';
    this.LOOKUP_TYPE_ICMS_CLAIM_TYPE_LINK = 'ICMS_CLAIM_TYPE_LINK';
    this.LOOKUP_TYPE_ICMS_CV_CODE = 'ICMS_CV_CODE';
    this.LOOKUP_TYPE_ICMS_MEDICAL_POLICY = 'ICMS_MEDICAL_POLICY';
    this.LOOKUP_TYPE_ICMS_CHANGE_SOURCE = 'ICMS_CHANGE_SOURCE';
    this.LOOKUP_TYPE_ICMS_REASON_CODES = 'ICMS_REASON_CODES';
    this.LOOKUP_TYPE_ICMS_POLICY_TYPES = 'ICMS_POLICY_TYPE';
    this.LOOKUP_TYPE_ICMS_REF_TITLE = 'ICMS_REF_TITLE';
    this.LOOKUP_TYPE_PROC_CODE_TYPE = 'PROC_CODES_TYPE';
    this.LOOKUP_TYPE_PROC_CODE_OPTION = 'PROC_CODES_OPTION';

    this.LOOKUP_CODE_EDITORIAL = "E";
    this.LOOKUP_CODE_LOGICAL = "L";
    this.LOOKUP_CODE_DENY = "DNY";
    this.LOOKUP_CODE_BILLED_WITH_OR = "BLW_OR";
    this.LOOKUP_CODE_BILLED_WITH_AND = "BLW_AND";
    this.LOOKUP_CODE_BILLED_WITHOUT_OR = "BLWO_OR";
    this.LOOKUP_CODE_BILLED_WITHOUT_AND = "BLWO_AND";
    this.LOOKUP_CODE_DENYO = "DNYO"
    this.NEW_FILE= "NEW_FILE";
    this.EXISTING_FILE ="EXISTING_FILE";
    this.RULE_CODES_FILE ="RULE_CODES_FILE"
    this.ROWS_PER_PAGE_OPTIONS = [10,50,100,500,1000];

    this.SMALL_VERSION ="SMALL";
    this.LONG_VERSION  ="LONG";

  }
}
